### ISSUE TITLE
Error: El botón de álbumes inferior no direcciona a la lista de álbumes.

### ISSUE THREAD

**Issue by AFOstorR** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#56]
## **Comportamiento Esperado**
Que se genere un cambio de pantalla al dar click en el botón inferior de álbumes.

## **Comportamiento Actual**
No hay cambio alguno en la pantalla al dar click en el botón inferior de álbumes.

## **Contexto**
Dispositivo (emulado): Pixel 6
Versión de Android: Nougat (API 24)

## **Pasos para reproducir efecto**

Paso 1: Ingresar a la aplicación (por el homepage)
![image](https://user-images.githubusercontent.com/98657009/200145678-a5e42309-3719-47ed-b053-990b5cbf862e.png)

Al dar click en el botón inferior de álbumes no se ejecuta ninguna acción.
![image](https://user-images.githubusercontent.com/98657009/200130803-532139c3-0b0c-4adf-a672-231fba1338c0.png)

**Comment by dcastrog2uniandes** [comment]
Quedó resulto en el issue #62
