### ISSUE TITLE
Error: El botón de artistas inferior no direcciona a la lista de artistas.

### ISSUE THREAD

**Issue by AFOstorR** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#57]
## **Comportamiento Esperado**
Que se genere un cambio de pantalla al dar click en el botón inferior de artistas.

## **Comportamiento Actual**
No hay cambio alguno en la pantalla al dar click en el botón inferior de artistas.

## **Contexto**
Dispositivo (emulado): Pixel 6
Versión de Android: Nougat (API 24)

## **Pasos para reproducir efecto**

Paso 1: Ingresar a la aplicación (por el homepage)
![image](https://user-images.githubusercontent.com/98657009/200145678-a5e42309-3719-47ed-b053-990b5cbf862e.png)

Al dar click en el botón inferior para lista de artistas no se genera ningún cambio en la pantalla.
![image](https://user-images.githubusercontent.com/98657009/200130313-8f386720-97fe-4c07-a320-877ca13c1258.png)

**Comment by dcastrog2uniandes** [comment]
Quedó resulto en el issue #62
