### ISSUE TITLE
Error: El ícono de álbumes en la vista de home no direcciona a la lista de álbumes.

### ISSUE THREAD

**Issue by AFOstorR** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#58]
## **Comportamiento Esperado**
Que se genere un cambio de pantalla al dar click en el ícono de álbumes.

## **Comportamiento Actual**
No hay cambio alguno en la pantalla al dar click en el ícono de álbumes.

## **Contexto**
Dispositivo (emulado): Pixel 6
Versión de Android: Nougat (API 24)

## **Pasos para reproducir efecto**

Paso 1: Ingresar a la aplicación (por el homepage)
![image](https://user-images.githubusercontent.com/98657009/200145678-a5e42309-3719-47ed-b053-990b5cbf862e.png)

Al dar click sobre el ícono de álbumes  en la vista de home no se genera ningún cambio en la pantalla.
![image](https://user-images.githubusercontent.com/98657009/200129884-2cb934e3-e959-48e0-b5cb-ce5ea93e176f.png)

**Comment by dcastrog2uniandes** [comment]
Quedó resulto en el issue #62
