### ISSUE TITLE
Error: El ícono de artistas en la vista de home no direcciona a la lista de artistas.

### ISSUE THREAD

**Issue by AFOstorR** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#59]
## **Comportamiento Esperado**
Que se genere un cambio de pantalla al dar click en el ícono de artistas.

## **Comportamiento Actual**
No hay cambio alguno en la pantalla al dar click en el ícono de artistas.

## **Contexto**
Dispositivo (emulado): Pixel 6
Versión de Android: Nougat (API 24)

## **Pasos para reproducir efecto**

Paso 1: Ingresar a la aplicación (por el homepage)
![image](https://user-images.githubusercontent.com/98657009/200145678-a5e42309-3719-47ed-b053-990b5cbf862e.png)

Al dar click sobre el ícono de artistas en la vista de home no se genera ningún cambio en la pantalla.
![image](https://user-images.githubusercontent.com/98657009/200129814-e9da0604-e67a-4c78-aa7c-eba3be3f7197.png)

**Comment by dcastrog2uniandes** [comment]
Quedó resulto en el issue #62
