### ISSUE TITLE
Error: El login no corre en la versión API 22 (Lollipop)

### ISSUE THREAD

**Issue by dcastrog2uniandes** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#61]
El proyecto al ejecutarse en una API level 22 no corre

## **Comportamiento Esperado**
Ver Pantalla de Login

## **Comportamiento Actual**
Mensaje: Unfortunately, Vinilos Grupo 15 has stopped

## **Contexto**
Dispositivo (emulado): Pixel 6
Versión de Android: Lollipop (API 22)

## **Pasos para reproducir efecto**

![image](https://user-images.githubusercontent.com/99267339/200130373-b5b23f66-c53f-4d94-ab00-f58282f5d8f4.png)

**Comment by nbarreto80235** [comment]
Se soluciona error presentado con ImageView se cambia atributo app:srcCompact por android:src 
![SolucionLoginApi22](https://user-images.githubusercontent.com/35924986/200184071-8be42671-21df-40dc-b999-6b67015f49fe.png)
