### ISSUE TITLE
Error: Instalación duplicada de la app

### ISSUE THREAD

**Issue by dcastrog2uniandes** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#66]
## **Comportamiento Esperado**
Que al instalar el apk, la aplicación se instale una unica vez

## **Comportamiento Actual**
Al generar e instalar el apk en un dispositivo fisico, la aplicación queda duplicada

## **Pasos para reproducir efecto**
1. Descargar el apk
2. Instalar
3. Ver que se generan dos aplicaciones

## **Evidencias**

![vinilos duplicada](https://user-images.githubusercontent.com/99267339/200179900-4a098d4d-c76d-4c1a-a0aa-edccb4dbe218.jpeg)

## **Contexto**
 - Versión de la app: 1.0.0
 - Sistema Operativo: Android 10
 - Dispositivo: Xioami Note 7

**Comment by mcgomeztuniandes** [comment]
## **Solución**

Se valida el código de la aplicación y se detecta que en el manifiesto hay dos activity, se configura el login con activity principal,

Activity principal

android:name=".view.LoginActivity"
            android:exported="true">
<intent-filter>
                **<action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />**
            </intent-filter>

Al activity main se elimina que pueda lanzar el launch

Se genera un nuevo APK

## **Evidencia de la solución**

**Comment by dcastrog2uniandes** [comment]
Se realizan pruebas con el nuevo apk generado y se evidencia una única instalación. 

### **Evidencia**

![WhatsApp Image 2022-11-06 at 12 05 14 PM](https://user-images.githubusercontent.com/99267339/200184473-efc997ed-6cf7-48ef-8e43-56ebd23e788e.jpeg)

**Comment by dcastrog2uniandes** [comment]
Bug corregido
