### ISSUE TITLE
Error: El layout de detalle_album no se ajusta correctamente en dispositivos pequeños.

### ISSUE THREAD

**Issue by AFOstorR** [mcgomeztuniandes/MISW-4203-AplicacionesMoviles#69]
## **Comportamiento Esperado**
Que las imagenes y textos de la pantalla de detalle_album, se ajusten al tamaño de la pantalla del dispositivo.

## **Comportamiento Actual**
En dispositivos con tamaños de pantalla de 5.5" la pagina de detalle_album no se muestra correctamente. Las imagenes se muestran cortadas.

## **Pasos para reproducir efecto**
1. Lanzar la aplicación
2. Ir a la página de inicio.
3. Ir a la lista de álbumes.
4. Seleccionar un album.
5. Observar el detalle

## **Evidencias**

Dispositivo: Pixel XL (5.5")
![image](https://user-images.githubusercontent.com/98657009/202613042-73f0e6e8-3b5b-43d6-8e18-a10722ffd757.png)

**Visualización correcta**
Dispositivo: Pixel 6 Pro (6.7")
![image](https://user-images.githubusercontent.com/98657009/202613257-109e9746-4244-4859-8343-d6085aaeeaf8.png)

## **Contexto**
 - Versión de la app: 1.0.0
 - Dispositivo Móvil (Emulado): Pixel XL
 - Sistema operativo (versión): Android API Level 22 (Lollipop)

**Comment by dcastrog2uniandes** [comment]
Se rediseña vista para hacerla responsiva al tamaño de la pantalla


![Image](https://user-images.githubusercontent.com/99267339/202830653-baabcb39-f251-42ab-958c-92814bf669ad.png)
